version: '3'

# Named volumes
volumes:
  # MySQL Data
  co-sales-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: co-sales
    volumes:
      - co-sales-mysql-data:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: co_sales
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: co-sales-app
    volumes:
      - .:/var/www/app
    ports:
      - "85:8080"
    links:
      - mysql
